### PR TITLE
#6650 BugFix: Upgraded leaflet in kibana, made relevant changes.

### PR DESCRIPTION
**Pull request by varunsharma27**
[#6650](https://github.com/sirensolutions/kibi-internal/issues/6650) error clicking on map after creating polygon
Upgraded leaflet in kibi investigate, making relevant changes.

Have tested other plugins as well (Which rely on leaflet). Please merge this AFTER this is merged :- [#6942](https://github.com/sirensolutions/kibi-internal/pull/6942)

### CODE REVIEW

**Comment by szydan** [comment]
@varunsharma27 can you please add the usual gulp + gradle to this plugin 
I see that there is at least one test here, so it would be nice to run it in our build 
and also configure the PR builder to run for every PR 
Can be done in separate ticket

**Comment by szydan** [comment]
Sorry I see it is already there, just a dedicated PR builder is missing on Jenkins on build2 
I'll take care, and will set it up tomorrow

**Comment by varunsharma27** [comment]
Sure. 😉

**Comment by colmose** [comment]
jenkins test it

**Comment by colmose** [comment]
jenkins test it

**Comment by colmose** [comment]
jenkins test it

**Comment by varunsharma27** [comment]
Jenkins test it

**Comment by colmose** [comment]
jenkins test it

**Comment by varunsharma27** [comment]
jenkins test it

**Comment by colmose** [comment]
I guess this one won't pass until https://github.com/sirensolutions/kibi-internal/pull/6942 is landed, @varunsharma27?

**Comment by colmose** [comment]
jenkins test it

**Pull request merged**
