### PR TITLE
Event based spiderfying

### PR DESCRIPTION
**Pull request by corrigancd**
To handle overlapping individual documents on the map. 

The steps carried out in the GIF below are: 
- click on a marker
- the event uses the coordinates of the icon that is clicked
- finds the other points within a configurable radius
- spiderifies

unspiderfying takes place when the map is panned or zoomed

The plus is present on any marker where an overlap has been detected and the visibility is toggled when spiderfying.

Spiderfying changes from circular arrangement to spiral at a threshold of 30 points

On a layer with many features:
spiderfyingWorking

On a layer with smaller number of features:
spiderfyingWorkingSmallerNumberOfFeatures

### CODE REVIEW

**Comment by johnnylopes** [comment]
@jccq what do you think?

**Comment by jccq** [comment]
is this ONLY in the cae where the coordinates are IDENTICAL? if so should we not simply put a number?

**Comment by johnnylopes** [comment]
Well @jccq, you might want to see those points individually. It might contain some specific/relevant information, etc. This was a solution @corrigancd found. 
I don't know any use case, but it might be something nice to have.

**Comment by jccq** [comment]
@johnnylopes we dont have individual styling per node as we have on the graph. so its very limited the value of showing individual nodes (if not for the tooltip). So given we're in cluster mode.. a useful thing woudl be to simply have the number.. e.g. there s 5 on the same identical spot.. then write 5. I guess if this is alrady done ok.. but please write a number on those that are "spiders"
thans

**Comment by corrigancd** [comment]
Currently, the `+` appears when there are points (documents) that are within 10 pixels of one another

When a point with a `+`  is clicked, the spiderfying will expand points within 50 px

I found these to work well and they can be adjusted

The idea is that the plus is an indication that spiderfy is possible. Clustering is a good way to present the layer in its entirety and in the areas where point densities are lowest, the idea of viewing the popups of each individual point is likely a benefit to an analyst? 

Consider a normal use case like below. Picture A, where the points are very concentrated, but do not have exactly the same coordinates. Is it a benefit to have the option to spiderfy and view the details of individual points like in Picture B?
**A.**
image
**B.**
image


Counts can be done, is it as simple as finding the points that have identical coordinates and adding a count? If so, I feel there'll be times where the number will be blocked by other points...

**Comment by jccq** [comment]
ok lets try! make the + very visible. i didnt see it in the original gif it
wasnt clear i could click

**Comment by corrigancd** [comment]
Here are the plus's: 
image
image

**Pull request merged**
