### PR TITLE
INVE-11132 - Negative margin to remove padding introduced in viz container

### PR DESCRIPTION
**Pull request by mikehug**
Fix for issue raised here [INVE-11132] - we will review and merge when main UX branch in kibi-internal is merged

[INVE-11132]: https://sirensolutions.atlassian.net/browse/INVE-11132

### CODE REVIEW

**Comment by corrigancd** [comment]
@mikehug, can you post a screenshot of the vis loaded, on a dashboard with the Aggregations layer on the map? I think everything should be ok if that works

**Comment by mikehug** [comment]
You can run branch `frontend-ux-initial` on kibi-internal to see how them play together or visit https://s10-5-ux.volatile.siren.io/ to see a build with both branches already built

**Comment by mikehug** [comment]
image

**Comment by corrigancd** [comment]
@mikehug , thanks for volatile link. The padding is still there in vis edit mode:

image

**Comment by mikehug** [comment]
Not a problem there it is for dashboard view. Actually seeing this warning on the build:

**Comment by corrigancd** [comment]
There's a PR for that rn

**Pull request merged**
