### PR TITLE
Update drag icon color

### PR DESCRIPTION
**Pull request by niknbr**
### Description
Update default color of drag icons (=) so that they are visible (not sure if they are white by design. Ignore this PR if so.)

image

### CODE REVIEW

**Comment by szydan** [comment]
@mikehug please check this

**Comment by corrigancd** [comment]
Yeah, nice question, they are white, then grey on hover. This was the original Figma design,

**Comment by mikehug** [comment]
Yes, this came up. The problem is with the default EUI drag handle looks too much like an equals so recommended we use the dot drag 
`<i class="fas fa-grip-horizontal"></i>`

**Comment by niknbr** [comment]
> Yes, this came up. The problem is with the default EUI drag handle looks too much like an equals so recommended we use the dot drag
> `<i class="fas fa-grip-horizontal"></i>`
> 
> So try this in grey (no white).

Will update this

**Comment by niknbr** [comment]
image

Also fixes:
image

**Pull request merged**
