### PR TITLE
Fix for screen crash with geohash

### PR DESCRIPTION
**Pull request by corrigancd**
@johnnylopes , @poojah1 fix for - https://sirensolutions.atlassian.net/browse/INVE-11452

### CODE REVIEW

**Comment by johnnylopes** [comment]
thanks @corrigancd 
@poojah1 can you test that on branch?

**Comment by poojah1** [comment]
Hi @corrigancd , The current issue working as expected but I m facing another issue for ;click one below' option.

PFA video of the same.
Is it related to this fix or something different. Accordingly I will create another issue if it is not related to this issue.


[Screen Recording 2020-05-15 at 17.37.19.zip](https://github.com/sirensolutions/enhanced_tilemap/files/4635760/Screen.Recording.2020-05-15.at.17.37.19.zip)

**Comment by corrigancd** [comment]
Yes, I think it is unrelated

**Comment by szydan** [comment]
Guys please address the other issue in separate PR

**Pull request merged**
