### PR TITLE
Filter visualization tooltip now applies to other visualization the dashboard

### PR DESCRIPTION
**Pull request by corrigancd**
Should be merged after/together with https://github.com/sirensolutions/kibi-internal/pull/12366

### CODE REVIEW

**Comment by mikehug** [comment]
Can we get this reviewed and merged @szydan - it was something raised by sonic, would like to get it into a build.

**Comment by corrigancd** [comment]
This is the issue - https://sirensolutions.atlassian.net/browse/INVE-11784 .

There have been integration tests written (linked to issue)

I believe this PR fixes the problem, but  can't be fully sure because there is an issue is blocking the testing (including the integration test) - https://sirensolutions.atlassian.net/browse/INVE-11827

**Comment by mikehug** [comment]
Ah ok, let's get the tests and other issue fixed, we will be updating their environment regularly so we can aim to have these issue lined up for early in the next sprint @johnnylopes

**Comment by johnnylopes** [comment]
yes, that issue is already included as a priority for the next sprint. We could even include it on this sprint if we manage to fix the ones we have there.

**Comment by szydan** [comment]
@corrigancd please review - I can not assign you as you are the author of this PR

**Comment by szydan** [comment]
> Out of interest, is title added to sirenMeta close for any reason, is it completeness
Just completeness and a bit easier to debug things if the correct title is there

**Pull request merged**
