### PR TITLE
Indicating that a layer is a stored layer type

### PR DESCRIPTION
**Pull request by corrigancd**
The brief is that we need a way to identify that layers are a Stored Layer type, how about this: 

Option 1:
IndicatingAStoredLayerType

### CODE REVIEW

**Comment by szydan** [comment]
Two many icons 
In general more layers will be coming from Elastic 
so what if we mark somehow the other few layers which are NOT coming from ES ?

**Comment by corrigancd** [comment]
@szydan Any better? 
image

**Comment by jccq** [comment]
waaaait! this is bad. it was so nice and clean 
we can do this on hover! show a tooltip?

**Comment by jccq** [comment]
please add it to the tooltip add +"(Elasticsearch stored layer)" even though again i am not sure why we want to say that.

**Comment by corrigancd** [comment]
> waaaait! this is bad. it was so nice and clean
> we can do this on hover! show a tooltip?

They want a way to identify Stored Layers from the other types. This means without hovering, I would think?: 
image

**Comment by jccq** [comment]
Reading it it makes me think more like a line between the types of layers.
like all those from regular then a line all those from aggregations then a line all those from etc..
can we try a subtle line to separate them ? (segregate them?)

**Comment by szydan** [comment]
@jccq @corrigancd line separator would be nice but then we allow to drag and reorder them so NO

**Comment by szydan** [comment]
@corrigancd the second option is better because on average I expect less non-es layers 
Not perfect but better 
Maybe @mrcznl can help us here

**Comment by johnnylopes** [comment]
yeah, I also don't think the tooltip would be okay for them according to what they said above. 

What I really think they want is something like this:

**Default layers**
Geo filters
Aggregations

**Stored Layers**
world countries

but then we would have to change the drag and drop logic.

So maybe we need something on the layer itself. Another icon might be too much yeah, maybe a default color or small css for stored layers which is not an icon but can indicate that.

**Comment by jccq** [comment]
@szydan is right. a line breaks the drag and drop.

the only thing is the tooltip for now. (not the icon please..) I'll talk to them later

**Comment by johnnylopes** [comment]
What is the final decision here? tooltip or pipe line?

**Comment by szydan** [comment]
@johnnylopes just tooltip for now

**Comment by johnnylopes** [comment]
We already have a trash bin icon just for stored layers which distinguishes between them, maybe it was not enough for them.

So, for the default layers, we could make them grey (kind of disabled), because we cannot delete them anyway.

As my message was too late, let's stick with the tooltip for this version and check their feedback.

**Comment by corrigancd** [comment]
Here's progress on the tooltip. Some points and I suggest someone else picks this up: 

- The Ellipsis with tooltip component didn't allow for the tooltip to be different from the current truncated label
- I replaced this with the react-texty (https://www.npmjs.com/package/react-texty) component so that I could add `Stored Layer:` to the beginning of the tooltip
- Note from the GIF that tooltips don't appear when a layer is NOT truncated, some type of reworking would be required for this. 

StoredLayerTooltipProgress

**Comment by jccq** [comment]
@corrigancd unfortunately its messy and detracts from the rest.

ok how about to show a "I" (info) icon just on hover (right most).. hovering on that icon would then show the tooltip - i really dont think sseeing this information is that important i just dont want to get the component ugly for this!!

**Comment by corrigancd** [comment]
Sounds good, so if I have it right: 
No icon is present on layer control
Then when you hover on a stored layer, an (i) appears to the right of a stored layer
Then when you hover on the (i) a tooltip appears indicating that the layer is a stored layer

@szydan @johnnylopes, does this sound like a viable solution?

**Comment by johnnylopes** [comment]
Well, that's fine.  

In the end, they will be validating this, so let's not spend a lot of time with what we don't even know if it is okay for them. 
Plus we gonna be improving more things later (`e.g` indentation of trash bin icons, cropping, etc).

**Comment by szydan** [comment]
@jccq @corrigancd @johnnylopes 
Guys hover on top of a hover is not optimal either 
Lets just make normal hover with 250ms delay 
and in that hover you put all information we want

**Comment by jccq** [comment]
@szydan awesome you're right just put a big delay like 1000 ms? (given its ugly and useless)
thanks!!

**Comment by corrigancd** [comment]
delay of 1000 ms added

**Pull request merged**
