### PR TITLE
Bumped gulp version from 13.9.1 to 14.0.2

### PR DESCRIPTION
**Pull request by AjayKumar4**
sirensolutions/kibi-internal#10819
Bumped gulp version from 13.9.1 to 14.0.2

### CODE REVIEW

**Comment by AjayKumar4** [comment]
1. remove node_module
2. npm install 
3. gulp  sync / gulp dev

**Comment by szydan** [comment]
@AjayKumar4 can you add a script to package.json 

```
sync: gulp sync
```
and then test with 
```
npm run sync 
```
This way it will work without global gulp 
Then I would like such script to be added to all our repos where we use gulp sync task

Also can you squash all the commit into one please

**Comment by AjayKumar4** [comment]
image

**Comment by AjayKumar4** [comment]
use this SHA for backporting this changes 6ce8bc8b2f531e8c4d03e947c58b880366ce50cb

**Pull request merged**
